// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitializeEvent(pharse string) (Event, error) {
	message := NewMessage(pharse)
	greeter := NewGreeter(message)
	event := NewEvent(greeter)
	return event, nil
}
